# Generated by Django 5.2.8 on 2025-11-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_mobile',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='project_manager',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
