# Generated by Django 5.2.8 on 2025-11-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_bill_customer_address_bill_customer_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_value',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
