# Generated by Django 5.2.8 on 2025-11-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_barcode_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode_value',
        ),
    ]
