# Generated by Django 5.2.8 on 2025-11-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_barcode_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='project_manager',
        ),
        migrations.AddField(
            model_name='bill',
            name='project_managers',
            field=models.ManyToManyField(blank=True, related_name='bills', to='inventory.teammember'),
        ),
    ]
