# Generated by Django 5.2.8 on 2025-11-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_teammember_remove_bill_project_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='project_managers',
        ),
        migrations.AddField(
            model_name='bill',
            name='project_manager',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
