# Generated by Django 5.2.8 on 2025-11-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
